version: "3"

tasks:
  build:
    cmds:
      - docker compose build --no-cache
    silent: true
  up:
    cmds:
      - docker compose up -d
    silent: true
  down:
    cmds:
      - docker compose down
    silent: true
  shell:
    cmds:
      - docker compose exec -it python sh
    silent: true
  lint:
    cmds:
      - docker compose exec -it python flake8 ./src/
      - docker compose exec -it python mypy ./src/
    silent: true
  format:
    cmds:
      - docker compose exec -it python isort ./src/
      - docker compose exec -it python black ./src/
    silent: true
  run:
    cmds:
      - docker compose exec -it python python ./src/main.py
    silent: true
